name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} compile

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 51c8124045ec5b7c6d342b94a4020ed2f7fda496

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Compile Java sources
      run: |
        ./gradlew clean build -x test 
